name       : devhelp
version    : 3.38.0
release    : 23
source     :
    - https://download.gnome.org/sources/devhelp/3.38/devhelp-3.38.0.tar.xz : 918efb173122b26d45fa51c194a0b659e63fee7705f6722db2534fabc3452369
license    : GPL-2.0-only
component  : programming.tools
summary    : API documentation browser for GNOME
description: |
    Devhelp is an API documentation browser for GTK+ and GNOME. It works natively with GTK-Doc (the API reference system developed for GTK+ and used throughout GNOME for API documentation). If you use GTK-Doc with your project, you can use Devhelp to browse the documentation.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(python3)
    - pkgconfig(webkit2gtk-4.0)
    - gtk-doc
    - intltool
    - itstool
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
