name       : devhelp
version    : 3.36.2
release    : 22
source     :
    - https://download.gnome.org/sources/devhelp/3.36/devhelp-3.36.2.tar.xz : 8b5a84319efbb2ef1bc4022ee3ed2d6678794eba2dfa993e50e03d6e7b930c5e
license    : GPL-2.0-only
component  : programming.tools
summary    : API documentation browser for GNOME
description: |
    Devhelp is an API documentation browser for GTK+ and GNOME. It works natively with GTK-Doc (the API reference system developed for GTK+ and used throughout GNOME for API documentation). If you use GTK-Doc with your project, you can use Devhelp to browse the documentation.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(python3)
    - pkgconfig(webkit2gtk-4.0)
    - gtk-doc
    - intltool
    - itstool
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
