name       : devhelp
version    : 3.24.0
release    : 10
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/devhelp/3.24/devhelp-3.24.0.tar.xz : 4858de1c815532ad160d1bf9facd28859972e3a052908a8edf73f866c8cce430
license    : GPL-2.0
component  : programming.tools
summary    : API documentation browser for GNOME
description: Devhelp is an API documentation browser for GTK+ and GNOME. It works natively with GTK-Doc (the API reference system developed for GTK+ and used throughout GNOME for API documentation). If
    you use GTK-Doc with your project, you can use Devhelp to browse the documentation.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(python-3.5)
    - pkgconfig(webkit2gtk-4.0)
    - intltool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
